### ISSUE TITLE
Add a reusable github action 

### ISSUE THREAD

**Issue by mkoertgen** [solugo/gitversion#3]
Add an example `action.yml` in this repo so that it can be re-used as a GitHub Action, cf.:
- https://docs.github.com/en/actions/creating-actions
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses

Example github workflow:

```
jobs:
  version:
     steps:
        - uses solgo/actions/gitversion@<ref>
           ... output ...
```

GitHub recommends to place actions in separate repos, cf.:
- https://docs.github.com/en/actions/creating-actions/about-custom-actions#choosing-a-location-for-your-action
